# Site settings
title: Flatiron Experience
header-img: img/home-bg.png
email: christiatidwell@bellsouth.net
copyright_name: DeedaG
description: > # this means to ignore newlines until "baseurl:"
  Learning to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DeedaG
learn_profile: DeedaG
email_username: christiatidwell@bellsouth.net

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
